dist: xenial
language: cpp
compiler:
  - clang

addons:
  apt:
    packages:
      - libboost-test-dev

script:
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
